name: 🐛 Bug Report
description: Report an issue with the repository
title: "[BUG] "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! 🐛

  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Type
      description: What type of issue are you experiencing?
      options:
        - Formatting/Display Issue
        - Broken Link
        - Incorrect Information
        - Missing Information
        - Duplicate Content
        - Other
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what you expected to happen and what actually happened
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where in the repository did you find this issue?
      placeholder: e.g., "README.md line 245", "Machine Learning section", "Contributing guidelines"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here or paste image URLs
    validations:
      required: false

  - type: input
    id: browser
    attributes:
      label: Browser (if applicable)
      description: Which browser are you using?
      placeholder: e.g., Chrome 96, Firefox 95, Safari 15
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have provided sufficient detail to reproduce the issue
          required: true
